MapTiDB2PG:
  - TiDB:
      DataType: BOOL
      Def: t_bool BOOL
    PG:
      DataType: BOOL
      Def: t_bool BOOL
    Value: true
  - TiDB:
      DataType: TINYINT
      Def: t_tinyint TINYINT DEFAULT 10
    PG:
      DataType: SMALLINT
      Def: t_tinyint SMALLINT
    Value: 1
  - TiDB:
      DataType: SMALLINT
      Def: t_smallint SMALLINT UNSIGNED
    PG:
      DataType: INT
      Def: t_smallint INT
    Value: 1000
  - TiDB:
      DataType: MEDIUMINT
      Def: t_mediumint MEDIUMINT NOT NULL default 10
    PG:
      DataType: INT
      Def: t_mediumint INT
    Value: 1000
  - TiDB:
      DataType: INT
      Def: t_int INT
    PG:
      DataType: INT
      Def: t_int INT
    Value: 1000
  - TiDB:
      DataType: BIGINT
      Def: t_bigint BIGINT
    PG:
      DataType: BIGINT
      Def: t_bigint BIGINT
    Value: 10000
  - TiDB:
      DataType: BIGINT UNSIGNED 
      Def: t_bigint_unsigned BIGINT UNSIGNED
    PG:
      DataType: BIGINT
      Def: t_bigint_unsigned BIGINT
    Value: 10000
  - TiDB:
      DataType: TINYBLOB
      Def: t_tinyblob TINYBLOB
    PG:
      DataType: bytea
      Def: t_tinyblob VARBYTE
      #      DataType: text
      #      Def: t_tinyblob text
    Value: <<<<This is the test>>>>
  - TiDB:
      DataType: BLOB
      Def: t_blob BLOB
    PG:
      DataType: text
      Def: t_blob VARBYTE
    Value: <<<<This is the blob test message>>>>
  - TiDB:
      DataType: MEDIUMBLOB
      Def: t_mediumblob MEDIUMBLOB
    PG:
      DataType: text
      Def: t_mediumblob VARBYTE
    Value: <<<<This is the mediumblob message>>>>
  - TiDB:
      DataType: LONGBLOB
      Def: t_longblob LONGBLOB
    PG:
      DataType: text
      Def: t_longblob VARBYTE
    Value: <<<<This is the longblob message>>>>
  - TiDB:
      DataType: BINARY
      Def: t_binary BINARY
    PG:
      DataType: VARBYTE
      Def: t_binary VARBYTE
    Value: <<<<t>>>>
  - TiDB:
      DataType: VARBINARY
      Def: t_varbinary VARBINARY(256)
    PG:
      DataType: VARBYTE
      Def: t_varbinary VARBYTE
    Value: <<<<This is the barbinary message>>>>
  - TiDB:
      DataType: TINYTEXT
      Def: t_tinytext TINYTEXT
    PG:
      DataType: VARCHAR
      Def: t_tinytext VARCHAR
    Value: <<<<This is TiNYTEXT>>>>
  - TiDB:
      DataType: TEXT
      Def: t_text TEXT
    PG:
      DataType: VARCHAR
      Def: t_text VARCHAR
    Value: <<<<This is TEXT>>>>
  - TiDB:
      DataType: MEDIUMTEXT
      Def: t_mediumtext MEDIUMTEXT NOT NULL
    PG:
      DataType: VARCHAR
      Def: t_mediumtext VARCHAR NOT NULL
    Value: <<<<This is medium text>>>>
  - TiDB:
      DataType: LONGTEXT
      Def: t_longtext LONGTEXT
    PG:
      DataType: VARCHAR
      Def: t_longtext VARCHAR
    Value: <<<<This is long text>>>>
  - TiDB:
      DataType: CHAR
      Def: t_char CHAR
    PG:
      DataType: CHAR
      Def: t_char char
    Value: <<<<a>>>>
  - TiDB:
      DataType: VARCHAR
      Def: t_varchar VARCHAR(255) NOT NULL
    PG:
      DataType: VARCHAR
      Def: t_varchar VARCHAR(255) NOT NULL
    Value: <<<<a>>>>
  - TiDB:
      DataType: FLOAT 
      Def: t_float FLOAT
    PG:
      DataType: NUMERIC
      Def: t_float NUMERIC(18, 6)
    Value: 10.123456789
  - TiDB:
      DataType: DOUBLE
      Def: t_double DOUBLE
    PG:
      DataType: NUMERIC
      Def: t_double NUMERIC(18, 9)
    Value: 10.123456789
  - TiDB:
      DataType: DATETIME
      Def: t_datetime DATETIME
    PG:
      DataType: TIMESTAMP
      Def: t_datetime TIMESTAMP
    Value: <<<<2022-08-01 11:34:56>>>>
  - TiDB:
      DataType: DATE
      Def: t_date DATE
    PG:
      DataType: DATE
      Def: t_date DATE
    Value: <<<<2022-08-01>>>>
  - TiDB:
      DataType: TIMESTAMP
      Def: t_timestamp TIMESTAMP
    PG:
      DataType: TIMESTAMP
      Def: t_timestamp TIMESTAMP
    Value: <<<<2022-08-01 11:34:56>>>>
  - TiDB:
      DataType: TIME
      Def: t_time TIME
    PG:
      DataType: TIME
      Def: t_time TIME
    Value: <<<<11:23:09>>>>
  - TiDB:
      DataType: YEAR
      Def: t_year YEAR
    PG:
      DataType: SMALLINT
      Def: t_year SMALLINT
    Value: 2022
  - TiDB:
      DataType: BIT
      Def: t_bit BIT
    PG:
      DataType: BIT
      Def: t_bit BIT
    Value: 1
  - TiDB:
      DataType: JSON
      Def: t_json JSON
    PG:
      DataType: VACHAR
      Def: t_json VARCHAR
    Value: <<<<{\\\"testKey\\\":\\\"testValue\\\"}>>>>
  - TiDB:
      DataType: ENUM
      Def: t_enum enum("a", "b", "c")
    PG:
      DataType: VARCHAR
      Def: t_enum VARCHAR
    Value: <<<<a>>>>
  - TiDB:
      DataType: SET
      Def: t_set SET('"'"'a'"'"','"'"'b'"'"','"'"'c'"'"')
    PG:
      DataType: VARCHAR
      Def: t_set VARCHAR
    Value: <<<<a,b>>>>
  - TiDB:
      DataType: DECIMAL
      Def: t_decimal DECIMAL(20, 10)
    PG:
      DataType: DECIMAL
      Def: t_decimal DECIMAL(20, 10)
    Value: 10.123456789
