Meta:
  TableName: test01
  Source:
    DBType: tidb
    DBName: test
    PK: pk_col BIGINT PRIMARY KEY AUTO_RANDOM
    Executor: /opt/scripts/run_tidb_query
    TailColumns:
      - tidb_timestamp timestamp default current_timestamp
  Target:
    DBType: redshift 
    DBName: dev
    PK: pk_col bigint PRIMARY KEY
    Executor: /opt/scripts/run_redshift_query
    TailColumns:
      - tidb_timestamp timestamp
      - pg_timestamp timestamp default current_timestamp
Mapping:
  - Source:
      DataType: BOOL
      Def: t_bool BOOL
    Target:
      DataType: BOOL
      Def: t_bool BOOL
    Value: true
  - Source:
      DataType: TINYINT
      Def: t_tinyint TINYINT DEFAULT 10
    Target:
      DataType: SMALLINT
      Def: t_tinyint SMALLINT
    Value: 1
  - Source:
      DataType: SMALLINT
      Def: t_smallint SMALLINT UNSIGNED
    Target:
      DataType: INT
      Def: t_smallint INT
    Value: 1000
  - Source:
      DataType: MEDIUMINT
      Def: t_mediumint MEDIUMINT NOT NULL default 10
    Target:
      DataType: INT
      Def: t_mediumint INT
    Value: 1000
  - Source:
      DataType: INT
      Def: t_int INT
    Target:
      DataType: INT
      Def: t_int INT
    Value: 1000
  - Source:
      DataType: BIGINT
      Def: t_bigint BIGINT
    Target:
      DataType: BIGINT
      Def: t_bigint BIGINT
    Value: 10000
  - Source:
      DataType: BIGINT UNSIGNED 
      Def: t_bigint_unsigned BIGINT UNSIGNED
    Target:
      DataType: BIGINT
      Def: t_bigint_unsigned BIGINT
    Value: 10000
  - Source:
      DataType: TINYBLOB
      Def: t_tinyblob TINYBLOB
    Target:
      DataType: bytea
      Def: t_tinyblob VARBYTE
      #      DataType: text
      #      Def: t_tinyblob text
    Value: <<<<This is the test>>>>
  - Source:
      DataType: BLOB
      Def: t_blob BLOB
    Target:
      DataType: text
      Def: t_blob VARBYTE
    Value: <<<<This is the blob test message>>>>
  - Source:
      DataType: MEDIUMBLOB
      Def: t_mediumblob MEDIUMBLOB
    Target:
      DataType: text
      Def: t_mediumblob VARBYTE
    Value: <<<<This is the mediumblob message>>>>
  - Source:
      DataType: LONGBLOB
      Def: t_longblob LONGBLOB
    Target:
      DataType: text
      Def: t_longblob VARBYTE
    Value: <<<<This is the longblob message>>>>
  - Source:
      DataType: BINARY
      Def: t_binary BINARY
    Target:
      DataType: VARBYTE
      Def: t_binary VARBYTE
    Value: <<<<t>>>>
  - Source:
      DataType: VARBINARY
      Def: t_varbinary VARBINARY(256)
    Target:
      DataType: VARBYTE
      Def: t_varbinary VARBYTE
    Value: <<<<This is the barbinary message>>>>
  - Source:
      DataType: TINYTEXT
      Def: t_tinytext TINYTEXT
    Target:
      DataType: VARCHAR
      Def: t_tinytext VARCHAR
    Value: <<<<This is TiNYTEXT>>>>
  - Source:
      DataType: TEXT
      Def: t_text TEXT
    Target:
      DataType: VARCHAR
      Def: t_text VARCHAR
    Value: <<<<This is TEXT>>>>
  - Source:
      DataType: MEDIUMTEXT
      Def: t_mediumtext MEDIUMTEXT NOT NULL
    Target:
      DataType: VARCHAR
      Def: t_mediumtext VARCHAR NOT NULL
    Value: <<<<This is medium text>>>>
  - Source:
      DataType: LONGTEXT
      Def: t_longtext LONGTEXT
    Target:
      DataType: VARCHAR
      Def: t_longtext VARCHAR
    Value: <<<<This is long text>>>>
  - Source:
      DataType: CHAR
      Def: t_char CHAR
    Target:
      DataType: CHAR
      Def: t_char char
    Value: <<<<a>>>>
  - Source:
      DataType: VARCHAR
      Def: t_varchar VARCHAR(255) NOT NULL
    Target:
      DataType: VARCHAR
      Def: t_varchar VARCHAR(255) NOT NULL
    Value: <<<<a>>>>
  - Source:
      DataType: FLOAT 
      Def: t_float FLOAT
    Target:
      DataType: NUMERIC
      Def: t_float NUMERIC(18, 6)
    Value: 10.123456789
  - Source:
      DataType: DOUBLE
      Def: t_double DOUBLE
    Target:
      DataType: NUMERIC
      Def: t_double NUMERIC(18, 9)
    Value: 10.123456789
  - Source:
      DataType: DATETIME
      Def: t_datetime DATETIME
    Target:
      DataType: TIMESTAMP
      Def: t_datetime TIMESTAMP
    Value: <<<<2022-08-01 11:34:56>>>>
  - Source:
      DataType: DATE
      Def: t_date DATE
    Target:
      DataType: DATE
      Def: t_date DATE
    Value: <<<<2022-08-01>>>>
  - Source:
      DataType: TIMESTAMP
      Def: t_timestamp TIMESTAMP
    Target:
      DataType: TIMESTAMP
      Def: t_timestamp TIMESTAMP
    Value: <<<<2022-08-01 11:34:56>>>>
  - Source:
      DataType: TIME
      Def: t_time TIME
    Target:
      DataType: TIME
      Def: t_time TIME
    Value: <<<<11:23:09>>>>
  - Source:
      DataType: YEAR
      Def: t_year YEAR
    Target:
      DataType: SMALLINT
      Def: t_year SMALLINT
    Value: 2022
  - Source:
      DataType: BIT
      Def: t_bit BIT
    Target:
      DataType: BIT
      Def: t_bit BIT
    Value: 1
  - Source:
      DataType: JSON
      Def: t_json JSON
    Target:
      DataType: VACHAR
      Def: t_json VARCHAR
    Value: <<<<{\\\"testKey\\\":\\\"testValue\\\"}>>>>
  - Source:
      DataType: ENUM
      Def: t_enum enum("a", "b", "c")
    Target:
      DataType: VARCHAR
      Def: t_enum VARCHAR
    Value: <<<<a>>>>
  - Source:
      DataType: SET
      Def: t_set SET('"'"'a'"'"','"'"'b'"'"','"'"'c'"'"')
    Target:
      DataType: VARCHAR
      Def: t_set VARCHAR
    Value: <<<<a,b>>>>
  - Source:
      DataType: DECIMAL
      Def: t_decimal DECIMAL(20, 10)
    Target:
      DataType: DECIMAL
      Def: t_decimal DECIMAL(20, 10)
    Value: 10.123456789
