AWSTemplateFormatVersion: 2010-09-09
Description: >-
     The template is used to deploy aurora-mysql. 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Meta Configuration"
        Parameters:
          - InstanceType
          - VpcCidr
          - username
          - password
Parameters:
  InstanceType:
    Description: RDS instance type
    Type: String
    Default: db.r5.2xlarge
    AllowedValues:
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r5.4xlarge
    - db.r5.8xlarge
    - db.r5.12xlarge
    - db.r5.16xlarge
    - db.r5.24xlarge
    ConstraintDescription: must be a valid rdb instance type
  VpcCidr:
    Type: String
    Default: 172.83.0.0/16
    Description: The cidr of RDB
  username:
    Type: String
    Description: The username for RDB
  password:
    Type: String
    Description: The password of RDB
Resources:
  auroraMySQLVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'

  auroraMySQLSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: auroraMySQLVPC
      CidrBlock: !Select [ 0, !Cidr [ !Ref VpcCidr, 12, 8  ]  ]
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Scope
          Value: private
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  auroraMySQLSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: auroraMySQLVPC
      CidrBlock: !Select [ 1, !Cidr [ !Ref VpcCidr, 12, 8  ]  ]
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Scope
          Value: private
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  auroraMySQLRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: auroraMySQLVPC
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Scope
          Value: private
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  auroraMySQLSubnetRouteTableAssociation01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: auroraMySQLSubnet01
      RouteTableId:
        Ref: auroraMySQLRT
  auroraMySQLSubnetRouteTableAssociation02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: auroraMySQLSubnet02
      RouteTableId:
        Ref: auroraMySQLRT
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB access from client
      VpcId:
        Ref: auroraMySQLVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  auroraMySQLDBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        - Ref: auroraMySQLSubnet01
        - Ref: auroraMySQLSubnet02
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  RDSDBClusterParameterGroup: 
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties: 
      Description: "CloudFormation Sample Aurora Cluster Parameter Group"
      Family: aurora-mysql5.7
      Parameters: 
        time_zone: Asia/Tokyo
        binlog_format: ROW
        max_allowed_packet: 1073741824
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  RDSDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: CloudFormation Sample Aurora Parameter Group
      Family: aurora-mysql5.7
      Parameters:
        sql_mode: IGNORE_SPACE
        max_allowed_packet: 1024
        innodb_buffer_pool_size: '{DBInstanceClassMemory*3/4}'
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  RDSCluster: 
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties: 
      DBClusterIdentifier: tidb2aurora
      DBClusterParameterGroupName: 
        Ref: RDSDBClusterParameterGroup
      DBSubnetGroupName: 
        Ref: auroraMySQLDBSubnetGroup
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.10.1
      VpcSecurityGroupIds:
        - Ref: InstanceSecurityGroup
      MasterUserPassword: 
        Ref: password
      MasterUsername: 
        Ref: username
      StorageEncrypted: false
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  RDSDBInstance1: 
    Type: AWS::RDS::DBInstance
    Properties: 
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass:
        Ref: InstanceType
      DBParameterGroupName: 
        Ref: RDSDBParameterGroup
      Engine: aurora-mysql
      PubliclyAccessible: "false"
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
  RDSDBInstance2: 
    Type: AWS::RDS::DBInstance
    Properties: 
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass:
        Ref: InstanceType
      DBParameterGroupName: 
        Ref: RDSDBParameterGroup
      Engine: aurora-mysql
      PubliclyAccessible: "false"
      Tags:
        - Key: Cluster
          Value: ohmytiup-tidb2aurora
        - Key: Type
          Value: aurora
        - Key: Name
          Value: !Sub '${AWS::StackName}'
