version: "3"

services:
  app:
    image: ngoduykhanh/powerdns-admin:0.2.2
    container_name: powerdns_admin
    logging:
      driver: json-file
      options:
        max-size: 50m
    network_mode: host
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://{{ .TiDBUser }}:{{ .TiDBPass }}@{{ .TiDBHost }}:{{ .TiDBPort }}/{{ .TiDBName }}
      - GUINCORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
  pdns:
    image: emaxchou/pdns:4.2.0
    container_name: pdns
    network_mode: host
    volumes:
      - /opt/pdns/pdns.local.conf:/etc/pdns/conf.d/pdns.local.conf
    environment:
      - MYSQL_USER={{ .TiDBUser }}
      - MYSQL_PASS={{ .TiDBPass }}
      - MYSQL_HOST={{ .TiDBHost }}
      - MYSQL_PORT={{ .TiDBPort }}
    command:
      - --cache-ttl=120
      - --allow-axfr-ips=0.0.0.0/0
