AWSTemplateFormatVersion: 2010-09-09
Description: >-
     The template is used to deploy aurora-mysql. 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Meta Configuration"
        Parameters:
          - InstanceType
          - AuroraFamily
          - Engine
          - EngineVersion
          - VpcCidr
          - PubliclyAccessibleFlag
          - SingleMode
          - Username
          - Password
Parameters:
  InstanceType:
    Description: RDS instance type
    Type: String
    Default: db.r5.2xlarge
    AllowedValues:
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r5.4xlarge
    - db.r5.8xlarge
    - db.r5.12xlarge
    - db.r5.16xlarge
    - db.r5.24xlarge
    ConstraintDescription: must be a valid rdb instance type
  VpcCidr:
    Type: String
    Default: 172.83.0.0/16
    Description: The cidr of RDB
  AuroraFamily:
    Description: Aurora family
    Type: String
    Default: aurora-mysql8.0
    AllowedValues:
    - aurora-mysql5.7
    - mysql8.0
    - aurora-mysql8.0
    ConstraintDescription: Approriate aurora mysql family
  Engine:
    Type: String
    Default: aurora-mysql
    AllowedValues:
      - aurora-mysql
      - mysql
  EngineVersion:
    Type: String
    Default: 8.0.mysql_aurora.3.02.0
    AllowedValues:
      - 5.7.mysql_aurora.2.11.2
      - 8.0.29
      - 8.0.mysql_aurora.3.02.0
  Password:
    Type: String
    Description: The password of RDB
  Username:
    Type: String
    Description: The username for RDB
  PubliclyAccessibleFlag:
     Description: Public accessible
     Type: String
     Default: false
     AllowedValues:
       - true
       - false
  SingleMode:
     Description: Single mode or master-slave mode
     Type: String
     Default: true
     AllowedValues:
       - true
       - false

Conditions:
  IsPublic: !Equals
    - !Ref PubliclyAccessibleFlag
    - true
  IsMasterSlave: !Equals
    - !Ref SingleMode
    - false
  

Resources:
  auroraMySQLVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  theInternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: IsPublic

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: IsPublic
    Properties:
      InternetGatewayId:
        Ref: theInternetGateway
      VpcId:
        Ref: auroraMySQLVPC

  auroraMySQLSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: auroraMySQLVPC
      CidrBlock: !Select [ 0, !Cidr [ !Ref VpcCidr, 12, 8  ]  ]
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'

  auroraMySQLSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: auroraMySQLVPC
      CidrBlock: !Select [ 1, !Cidr [ !Ref VpcCidr, 12, 8  ]  ]
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'

  auroraMySQLRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: auroraMySQLVPC

  auroraMySQLSubnetRouteTableAssociation01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: auroraMySQLSubnet01
      RouteTableId:
        Ref: auroraMySQLRT

  auroraMySQLSubnetRouteTableAssociation02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: auroraMySQLSubnet02
      RouteTableId:
        Ref: auroraMySQLRT

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB access from client
      VpcId:
        Ref: auroraMySQLVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

  auroraMySQLDBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        - Ref: auroraMySQLSubnet01
        - Ref: auroraMySQLSubnet02

  RDSDBClusterParameterGroup: 
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties: 
      Description: "CloudFormation Sample Aurora Cluster Parameter Group"
      Family:
        Ref: AuroraFamily
      Parameters: 
        time_zone: Asia/Tokyo
        binlog_format: ROW

  RDSDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: CloudFormation Sample Aurora Parameter Group
      Family: 
        Ref: AuroraFamily
      Parameters:
        sql_mode: IGNORE_SPACE
        max_allowed_packet: 1024
        innodb_buffer_pool_size: '{DBInstanceClassMemory*3/4}'

  RDSCluster: 
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties: 
      DBClusterIdentifier: tidb2aurora
      DBClusterParameterGroupName: 
        Ref: RDSDBClusterParameterGroup
      DBSubnetGroupName: 
        Ref: auroraMySQLDBSubnetGroup
      Engine: 
        Ref: Engine
      EngineVersion: 
        Ref: EngineVersion
      VpcSecurityGroupIds:
        - Ref: InstanceSecurityGroup
      MasterUserPassword: 
        Ref: Password
      MasterUsername: 
        Ref: Username
      StorageEncrypted: false

  RDSDBInstance1: 
    Type: AWS::RDS::DBInstance
    Properties: 
      PubliclyAccessible: !Ref PubliclyAccessibleFlag
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass:
        Ref: InstanceType
      DBParameterGroupName: 
        Ref: RDSDBParameterGroup
      Engine: aurora-mysql

  RDSDBInstance2: 
    Type: AWS::RDS::DBInstance
    Condition: IsMasterSlave
    Properties: 
      PubliclyAccessible: !Ref PubliclyAccessibleFlag
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass:
        Ref: InstanceType
      DBParameterGroupName: 
        Ref: RDSDBParameterGroup
      Engine: aurora-mysql
